# -*- coding: utf-8 -*-
"""MIPRIMER_PROYECTO_PYNTHON.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Gmf22m6wNJT2P-t5Z1uounTVUBVpeKrh
"""

def saludar(nombre):
    print(f"¡Hola, {nombre}!")

def venta_electrodomesticos():
    Neveras = 6000000
    Lavadoras = 2500000
    Estufas = 1500000
    Hornos_Microhondas = 400000
    Barril_Asador = 800000
    Domicilio = 50000

    Total_Pagar = 0
    Opcion_Continuar = 1

    nombre = input("Bienvenido, Por favor me da su Nombre: ")
    saludar(nombre)

    while Opcion_Continuar == 1:
        print("Por favor elegir el producto que vas a comprar:")
        print("1. Neveras <- 6000000")
        print("2. Lavadoras <- 2500000")
        print("3. Estufas <- 1500000")
        print("4. Hornos Microondas <- 400000")
        print("5. Barril Asador <- 800000")

        Producto = int(input("Ingrese el número del producto: "))

        if Producto < 1 or Producto > 5:
            print("Opción no válida")
        else:
            Opcion_Domicilio = int(input("¿Desea llevarlo con domicilio? (1. Sí, 2. No): "))

            if Producto == 1:
                print("Has seleccionado una Nevera")
                Total_Pagar += Neveras
            elif Producto == 2:
                print("Has seleccionado una Lavadora")
                Total_Pagar += Lavadoras
            elif Producto == 3:
                print("Has seleccionado una Estufa")
                Total_Pagar += Estufas
            elif Producto == 4:
                print("Has seleccionado un Horno Microondas")
                Total_Pagar += Hornos_Microhondas
            elif Producto == 5:
                print("Has seleccionado un Barril Asador")
                Total_Pagar += Barril_Asador

            if Opcion_Domicilio == 1:
                Total_Pagar += Domicilio

            Opcion_Continuar = int(input("¿Desea comprar otro producto? (1. Sí, 2. No): "))

    print("Ofertas según medios de pago; 1. Efectivo 20% descuento, 2. T.Crédito si difieres a menos de 3 cuotas 5%, 4. Sistecredito No aplica Descuento")
    print("Elegir medio de pago: 1. Efectivo; 2. T. Crédito; 3. Mefia; 4. Sistecredito")

    Opcion_Pago = int(input("Ingrese el número del medio de pago: "))

    if Opcion_Pago < 1 or Opcion_Pago > 4:
        print("Opción de pago no válida")
    else:
        if Opcion_Pago == 1:
            print("Pago en efectivo, se aplica un 20% de descuento")
            Descuento = Total_Pagar * 0.20
            Total_Pagar -= Descuento
        elif Opcion_Pago == 2:
            print("Pago con tarjeta de crédito")
            Num_Cuotas = int(input("Ingrese el número de cuotas: "))
            if Num_Cuotas <= 3:
                print("Se aplica un 5% de descuento")
                Descuento = Total_Pagar * 0.05
                Total_Pagar -= Descuento
            else:
                print("No se aplica descuento")
        elif Opcion_Pago == 3:
            print("Pago con Mefia, se aplica un 40% de descuento")
            Descuento = Total_Pagar * 0.40
            Total_Pagar -= Descuento
        elif Opcion_Pago == 4:
            print("Pago con Sistecredito, no se aplica descuento")

    print(f"El total a pagar es: {Total_Pagar}")

# Ejecutar el algoritmo
venta_electrodomesticos()